// <auto-generated />
using System;
using GTMS.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GTMS.API.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GTMS.API.Models.CaiDat", b =>
                {
                    b.Property<int>("MaCaiDat")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TenDonViChuQuan");

                    b.Property<string>("TenKhoa");

                    b.Property<DateTime>("ThoiGianCapNhat");

                    b.Property<DateTime>("ThoiGianTao");

                    b.Property<int>("TrangThai");

                    b.HasKey("MaCaiDat");

                    b.ToTable("DanhSachCaiDat");
                });

            modelBuilder.Entity("GTMS.API.Models.DoAn", b =>
                {
                    b.Property<int>("MaDoAn")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("DiemTongKet");

                    b.Property<string>("LienKetTaiDoAn");

                    b.Property<int>("MaChuDe");

                    b.Property<int>("MaHocKy");

                    b.Property<int>("MaHoiDongBaoVe");

                    b.Property<int>("MaHuongNghienCuu");

                    b.Property<string>("MoTa");

                    b.Property<string>("NhanXetChung");

                    b.Property<string>("TenDoAn");

                    b.Property<DateTime>("ThoiGianBaoCao");

                    b.Property<DateTime>("ThoiGianCapNhat");

                    b.Property<DateTime>("ThoiGianTao");

                    b.Property<int>("TrangThai");

                    b.HasKey("MaDoAn");

                    b.HasIndex("MaHocKy");

                    b.HasIndex("MaHuongNghienCuu");

                    b.ToTable("DanhSachDoAn");
                });

            modelBuilder.Entity("GTMS.API.Models.GiangVien", b =>
                {
                    b.Property<string>("MaGiangVien");

                    b.Property<string>("DiaChi");

                    b.Property<string>("DonViCongTac");

                    b.Property<string>("Email");

                    b.Property<string>("GioiTinh");

                    b.Property<string>("HoVaTen");

                    b.Property<string>("HocHam");

                    b.Property<string>("HocVi");

                    b.Property<int?>("MaKhoa");

                    b.Property<DateTime>("NgaySinh");

                    b.Property<string>("QueQuan");

                    b.Property<string>("SoDienThoai");

                    b.Property<DateTime>("ThoiGianCapNhat");

                    b.Property<DateTime>("ThoiGianTao");

                    b.Property<int>("TrangThai");

                    b.HasKey("MaGiangVien");

                    b.HasIndex("MaKhoa");

                    b.ToTable("DanhSachGiangVien");
                });

            modelBuilder.Entity("GTMS.API.Models.HocKy", b =>
                {
                    b.Property<int>("MaHocKy");

                    b.Property<string>("NamHoc");

                    b.Property<string>("TenHocKy")
                        .IsRequired();

                    b.Property<DateTime>("ThoiGianBatDau");

                    b.Property<DateTime>("ThoiGianCapNhat");

                    b.Property<DateTime>("ThoiGianKetThuc");

                    b.Property<DateTime>("ThoiGianTao");

                    b.Property<int>("TrangThai");

                    b.HasKey("MaHocKy");

                    b.HasIndex("TenHocKy")
                        .IsUnique();

                    b.ToTable("DanhSachHocKy");
                });

            modelBuilder.Entity("GTMS.API.Models.HuongDanDoAn", b =>
                {
                    b.Property<string>("MaGiangVien");

                    b.Property<int>("MaDoAn");

                    b.Property<double>("Diem");

                    b.Property<string>("NhanXet");

                    b.Property<DateTime>("ThoiGianCapNhat");

                    b.Property<DateTime>("ThoiGianTao");

                    b.Property<int>("TrangThai");

                    b.HasKey("MaGiangVien", "MaDoAn");

                    b.HasIndex("MaDoAn");

                    b.ToTable("DanhSachHuongDanDoAn");
                });

            modelBuilder.Entity("GTMS.API.Models.HuongNghienCuu", b =>
                {
                    b.Property<int>("MaHuongNghienCuu");

                    b.Property<string>("TenHuongNghienCuu")
                        .IsRequired();

                    b.Property<DateTime>("ThoiGianCapNhat");

                    b.Property<DateTime>("ThoiGianTao");

                    b.Property<int>("TrangThai");

                    b.HasKey("MaHuongNghienCuu");

                    b.HasIndex("TenHuongNghienCuu")
                        .IsUnique();

                    b.ToTable("DanhSachHuongNghienCuu");
                });

            modelBuilder.Entity("GTMS.API.Models.Khoa", b =>
                {
                    b.Property<int>("MaKhoa");

                    b.Property<string>("TenKhoa")
                        .IsRequired();

                    b.Property<string>("TenVietTat")
                        .IsRequired();

                    b.Property<DateTime>("ThoiGianCapNhat");

                    b.Property<DateTime>("ThoiGianTao");

                    b.Property<int>("TrangThai");

                    b.HasKey("MaKhoa");

                    b.HasIndex("TenKhoa")
                        .IsUnique();

                    b.HasIndex("TenVietTat")
                        .IsUnique();

                    b.ToTable("DanhSachKhoa");
                });

            modelBuilder.Entity("GTMS.API.Models.KhoaDaoTao", b =>
                {
                    b.Property<int>("MaKhoaDaoTao");

                    b.Property<string>("TenKhoaDaoTao")
                        .IsRequired();

                    b.Property<string>("TenVietTat")
                        .IsRequired();

                    b.Property<DateTime>("ThoiGianBatDau");

                    b.Property<DateTime>("ThoiGianCapNhat");

                    b.Property<DateTime>("ThoiGianKetThuc");

                    b.Property<DateTime>("ThoiGianTao");

                    b.Property<int>("TrangThai");

                    b.HasKey("MaKhoaDaoTao");

                    b.HasIndex("TenKhoaDaoTao")
                        .IsUnique();

                    b.HasIndex("TenVietTat")
                        .IsUnique();

                    b.ToTable("DanhSachKhoaDaoTao");
                });

            modelBuilder.Entity("GTMS.API.Models.Lop", b =>
                {
                    b.Property<int>("MaLop");

                    b.Property<string>("HeDaoTao");

                    b.Property<int>("MaKhoa");

                    b.Property<int>("MaKhoaDaoTao");

                    b.Property<string>("TenLop")
                        .IsRequired();

                    b.Property<string>("TenVietTat")
                        .IsRequired();

                    b.Property<DateTime>("ThoiGianCapNhat");

                    b.Property<DateTime>("ThoiGianTao");

                    b.Property<int>("TrangThai");

                    b.HasKey("MaLop");

                    b.HasIndex("MaKhoa");

                    b.HasIndex("MaKhoaDaoTao");

                    b.HasIndex("TenLop")
                        .IsUnique();

                    b.HasIndex("TenVietTat")
                        .IsUnique();

                    b.ToTable("DanhSachLop");
                });

            modelBuilder.Entity("GTMS.API.Models.PhanBienDoAn", b =>
                {
                    b.Property<string>("MaGiangVien");

                    b.Property<int>("MaDoAn");

                    b.Property<DateTime>("ThoiGianCapNhat");

                    b.Property<DateTime>("ThoiGianTao");

                    b.Property<int>("TrangThai");

                    b.HasKey("MaGiangVien", "MaDoAn");

                    b.HasIndex("MaDoAn");

                    b.ToTable("DanhSachPhanBienDoAn");
                });

            modelBuilder.Entity("GTMS.API.Models.QuyDinh", b =>
                {
                    b.Property<int>("MaQuyDinh")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("GiaTri");

                    b.Property<string>("TenQuyDinh");

                    b.Property<DateTime>("ThoiGianCapNhat");

                    b.Property<DateTime>("ThoiGianTao");

                    b.Property<int>("TrangThai");

                    b.HasKey("MaQuyDinh");

                    b.ToTable("DanhSachQuyDinh");
                });

            modelBuilder.Entity("GTMS.API.Models.SinhVien", b =>
                {
                    b.Property<string>("MaSinhVien");

                    b.Property<string>("DiaChi");

                    b.Property<string>("Email");

                    b.Property<string>("GioiTinh");

                    b.Property<string>("HoVaTen");

                    b.Property<int?>("MaDoAn");

                    b.Property<int>("MaLop");

                    b.Property<DateTime>("NgaySinh");

                    b.Property<string>("QueQuan");

                    b.Property<string>("SoDienThoai");

                    b.Property<DateTime>("ThoiGianCapNhat");

                    b.Property<DateTime>("ThoiGianTao");

                    b.Property<int>("TrangThai");

                    b.HasKey("MaSinhVien");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("MaDoAn");

                    b.HasIndex("MaLop");

                    b.HasIndex("SoDienThoai")
                        .IsUnique()
                        .HasFilter("[SoDienThoai] IS NOT NULL");

                    b.ToTable("DanhSachSinhVien");
                });

            modelBuilder.Entity("GTMS.API.Models.TaiKhoan", b =>
                {
                    b.Property<int>("MaTaiKhoan")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("Hash");

                    b.Property<string>("PhanQuyen");

                    b.Property<byte[]>("Salt");

                    b.Property<string>("TenDangNhap");

                    b.Property<DateTime>("ThoiGianCapNhat");

                    b.Property<DateTime>("ThoiGianTao");

                    b.Property<int>("TrangThai");

                    b.HasKey("MaTaiKhoan");

                    b.ToTable("DanhSachTaiKhoan");
                });

            modelBuilder.Entity("GTMS.API.Models.ThanhVienHDBV", b =>
                {
                    b.Property<string>("MaDoAn");

                    b.Property<string>("MaGiangVien");

                    b.Property<string>("ChucVuHDBV");

                    b.Property<double>("Diem");

                    b.Property<int?>("DoAnMaDoAn");

                    b.Property<int>("MaChucVuHDBV");

                    b.Property<string>("NhanXet");

                    b.Property<DateTime>("ThoiGianCapNhat");

                    b.Property<DateTime>("ThoiGianTao");

                    b.Property<int>("TrangThai");

                    b.HasKey("MaDoAn", "MaGiangVien");

                    b.HasIndex("DoAnMaDoAn");

                    b.HasIndex("MaGiangVien");

                    b.ToTable("DanhSachThanhVienHDBV");
                });

            modelBuilder.Entity("GTMS.API.Models.DoAn", b =>
                {
                    b.HasOne("GTMS.API.Models.HocKy", "HocKy")
                        .WithMany()
                        .HasForeignKey("MaHocKy")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GTMS.API.Models.HuongNghienCuu", "HuongNghienCuu")
                        .WithMany("DoAn")
                        .HasForeignKey("MaHuongNghienCuu")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GTMS.API.Models.GiangVien", b =>
                {
                    b.HasOne("GTMS.API.Models.Khoa", "Khoa")
                        .WithMany("GiangVien")
                        .HasForeignKey("MaKhoa")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GTMS.API.Models.HuongDanDoAn", b =>
                {
                    b.HasOne("GTMS.API.Models.DoAn", "DoAn")
                        .WithMany("HuongDanDoAn")
                        .HasForeignKey("MaDoAn")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GTMS.API.Models.GiangVien", "GiangVien")
                        .WithMany("HuongDanDoAn")
                        .HasForeignKey("MaGiangVien")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GTMS.API.Models.Lop", b =>
                {
                    b.HasOne("GTMS.API.Models.Khoa", "Khoa")
                        .WithMany("Lop")
                        .HasForeignKey("MaKhoa")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GTMS.API.Models.KhoaDaoTao", "KhoaDaoTao")
                        .WithMany("Lop")
                        .HasForeignKey("MaKhoaDaoTao")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GTMS.API.Models.PhanBienDoAn", b =>
                {
                    b.HasOne("GTMS.API.Models.DoAn", "DoAn")
                        .WithMany("PhanBienDoAn")
                        .HasForeignKey("MaDoAn")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GTMS.API.Models.GiangVien", "GiangVien")
                        .WithMany("PhanBienDoAn")
                        .HasForeignKey("MaGiangVien")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GTMS.API.Models.SinhVien", b =>
                {
                    b.HasOne("GTMS.API.Models.DoAn", "DoAn")
                        .WithMany("SinhVien")
                        .HasForeignKey("MaDoAn")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GTMS.API.Models.Lop", "Lop")
                        .WithMany("SinhVien")
                        .HasForeignKey("MaLop")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GTMS.API.Models.ThanhVienHDBV", b =>
                {
                    b.HasOne("GTMS.API.Models.DoAn")
                        .WithMany("ThanhVienHDBV")
                        .HasForeignKey("DoAnMaDoAn");

                    b.HasOne("GTMS.API.Models.GiangVien", "GiangVien")
                        .WithMany("ThanhVienHDBV")
                        .HasForeignKey("MaGiangVien")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
